package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminPrivileges<M extends BaseAdminPrivileges<M>> extends Model<M> implements IBean {

    public java.lang.Integer getUserId() {
        return get("user_id");
    }

    public void setUserId(java.lang.Integer userId) {
        set("user_id", userId);
    }

    public java.lang.String getPrivileges() {
        return get("privileges");
    }

    public void setPrivileges(java.lang.String privileges) {
        set("privileges", privileges);
    }

}
