package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecommendedSite<M extends BaseRecommendedSite<M>> extends Model<M> implements IBean {

    public java.lang.Long getId() {
        return get("id");
    }

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.String getName() {
        return get("name");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getUrl() {
        return get("url");
    }

    public void setUrl(java.lang.String url) {
        set("url", url);
    }

    public java.lang.Long getType() {
        return get("type");
    }

    public void setType(java.lang.Long type) {
        set("type", type);
    }

}
