package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAward<M extends BaseUserAward<M>> extends Model<M> implements IBean {

    public java.lang.Long getUserId() {
        return get("user_id");
    }

    public void setUserId(java.lang.Long userId) {
        set("user_id", userId);
    }

    public java.lang.Long getAwardId() {
        return get("award_id");
    }

    public void setAwardId(java.lang.Long awardId) {
        set("award_id", awardId);
    }

    public java.lang.String getAwardName() {
        return get("award_name");
    }

    public void setAwardName(java.lang.String awardName) {
        set("award_name", awardName);
    }

}
