package com.demo.common.model;

import com.demo.common.model.base.BaseAdminPrivileges;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminPrivileges extends BaseAdminPrivileges<AdminPrivileges> {
    public static final AdminPrivileges dao = new AdminPrivileges();
}
