package com.demo.common.model;

import com.demo.common.model.base.BaseCategory;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
    public static final Category dao = new Category();

    /**
     * 查询菜单的子菜单
     */
    public List<Category> subContentTypes() {
        return dao.find("select * from category where parent_id = ?", new Object[]{get("id")});
    }


    public Category firstSubContentType(long parentId) {
        return dao.findFirst("select * from category where parent_id = ?", parentId);
    }
}
