package com.demo.common.model;

import com.demo.common.model.base.BaseRecommendedSite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecommendedSite extends BaseRecommendedSite<RecommendedSite> {
    public static final RecommendedSite dao = new RecommendedSite();
}
