package com.demo.common.model;

import com.demo.common.model.base.BaseUserAward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAward extends BaseUserAward<UserAward> {
    public static final UserAward dao = new UserAward();

}
