package com.demo.common.model;

import com.demo.common.model.base.BaseUser;
import com.jfinal.plugin.activerecord.Page;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User();

    public static String award(Long type) {
        if (type == 1) {
            return "国家千人计划";
        } else if (type == 2) {
            return "国家杰出青年基金获得者";
        } else if (type == 3) {
            return "国家级教学名师";
        } else if (type == 4) {
            return "国家优秀青年基金获得者";
        } else if (type == 5) {
            return "教育部“新世纪人才”";
        } else if (type == 6) {
            return "天津市千人计划";
        } else if (type == 7) {
            return "天津市中青年科技创新领军人才";
        } else if (type == 8) {
            return "天津市青年科技优秀人才";
        } else if (type == 9) {
            return "天津市重点领域创新团队";
        } else if (type == 10) {
            return "天津市青年拔尖人才";
        } else if (type == 11) {
            return "万人计划";
        } else if (type == 12) {
            return "天津市教学名师";
        } else if (type == 13) {
            return "天津市131创新团队";
        } else if (type == 14) {
            return "天津市131创新型人才工程第一层次";
        }
        return null;
    }

    public Page<User> paginate(int pageNumber, int pageSize) {
        return paginate(pageNumber, pageSize, "select *", "from user order by id asc");
    }

    public String laboratory() {
        if (this.getLaboratory() == 1) {
            return "先进高分子材料研究所";
        } else if (this.getLaboratory() == 2) {
            return "先进金属材料研究所";
        } else if (this.getLaboratory() == 3) {
            return "先进陶瓷研究所";
        } else if (this.getLaboratory() == 4) {
            return "焊接与先进制造技术研究所";
        } else if (this.getLaboratory() == 5) {
            return "新能源材料研究所";
        } else if (this.getLaboratory() == 6) {
            return "天津大学-日本国立物质材料研究所（NIMS）联合研究中心";
        } else if (this.getLaboratory() == 7) {
            return "教学与大型仪器实验中心";
        }
        return "其他";
    }

    public List<UserAward> getAwards() {
        return UserAward.dao.find("select * from user_award where user_id = ? order by award_id", this.getId());
    }

}
